### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by daite** [daite/angel-rs#3]
- [ ] dispatcher (network availability, etc..)
- [ ] error handling
- [ ] add more korea torrent site
- [ ] site select algorithm
